version: '2'
services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"
      - "5000:80"
    restart: always

  tetris:
    image: pomle/tetris-network-multiplayer
    restart: always

  snex-peer-server:
    image: snex/peer-server:ping
    restart: always

  snex-web:
    image: snex/web:v1.2.0
    environment:
      - URL_SELF=https://snex.io
      - URL_SNEX_LIB=https://cdn.snex.io/snex.v0.5.0.min.js
      - MEMCACHE_URL=memcached.snex.io:12197
    restart: always

  vibrant:
    image: pomle/vibrant
    restart: always
